// docs/blueprint/scaffold/src/domain/arena/BattleRecord.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.7.1

import { PetId } from '../pet/Pet';

export type BattleRecordId = string; // UUID v4

export type BattleOutcome = 'WIN' | 'LOSS' | 'DRAW';

export type BattleMode = 'RANKED' | 'CASUAL' | 'TOURNAMENT';

export interface RoundSnapshot {
  readonly round: number;           // 1-indexed round number
  readonly attackerPetId: PetId;
  readonly defenderPetId: PetId;
  readonly damageDealt: number;
  readonly defenderHpAfter: number;
}

export interface BattleRecordProps {
  readonly id: BattleRecordId;
  readonly mode: BattleMode;
  readonly challengerPetId: PetId;
  readonly opponentPetId: PetId;
  readonly winnerPetId: PetId | null;    // null on DRAW
  readonly loserPetId: PetId | null;     // null on DRAW
  readonly outcome: BattleOutcome;
  readonly rounds: readonly RoundSnapshot[];
  readonly xpAwarded: number;            // XP granted to the winner
  readonly rankedPointsDelta: number;    // Change in ranked points (can be negative)
  readonly startedAt: Date;
  readonly endedAt: Date;
}

/**
 * BattleRecord is an immutable ledger entry capturing the full result
 * of a single pet battle. It is never mutated after creation.
 */
export class BattleRecord {
  readonly id: BattleRecordId;
  readonly mode: BattleMode;
  readonly challengerPetId: PetId;
  readonly opponentPetId: PetId;
  readonly winnerPetId: PetId | null;
  readonly loserPetId: PetId | null;
  readonly outcome: BattleOutcome;
  readonly rounds: readonly RoundSnapshot[];
  readonly xpAwarded: number;
  readonly rankedPointsDelta: number;
  readonly startedAt: Date;
  readonly endedAt: Date;

  private constructor(props: BattleRecordProps) {
    this.id = props.id;
    this.mode = props.mode;
    this.challengerPetId = props.challengerPetId;
    this.opponentPetId = props.opponentPetId;
    this.winnerPetId = props.winnerPetId;
    this.loserPetId = props.loserPetId;
    this.outcome = props.outcome;
    this.rounds = props.rounds;
    this.xpAwarded = props.xpAwarded;
    this.rankedPointsDelta = props.rankedPointsDelta;
    this.startedAt = props.startedAt;
    this.endedAt = props.endedAt;
  }

  /**
   * Factory: records the outcome of a completed battle.
   * Validates that both pets are different, rounds array is non-empty,
   * and endedAt is after startedAt.
   */
  static record(props: Omit<BattleRecordProps, 'id'>): BattleRecord {
    throw new Error('Not implemented');
  }

  /**
   * Reconstitutes a BattleRecord from a persistence snapshot.
   */
  static reconstitute(props: BattleRecordProps): BattleRecord {
    throw new Error('Not implemented');
  }

  /** Duration of the battle in milliseconds. */
  durationMs(): number {
    throw new Error('Not implemented');
  }

  /** True if this record involves the given pet (as challenger or opponent). */
  involves(petId: PetId): boolean {
    throw new Error('Not implemented');
  }

  toJSON(): BattleRecordProps {
    throw new Error('Not implemented');
  }
}
