// docs/blueprint/scaffold/src/application/claim/ClaimService.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.8.2

import { ClaimCode, ClaimCodeId } from '../../domain/claim/ClaimCode';
import { PetRarity } from '../../domain/pet/PetRarity';
import { PetSpecies } from '../../domain/pet/Pet';
import { Pet } from '../../domain/pet/Pet';

export interface IssueClaimCodeCommand {
  speciesOverride?: PetSpecies;
  rarityOverride?: PetRarity;
  expiresAt: Date;
  /** ID of the admin user issuing the code */
  issuedByAdminId: string;
}

export interface RedeemClaimCodeCommand {
  /** The human-readable token string, e.g. "XFWR-4829-KQZL" */
  code: string;
  claimingUserId: string;
  /** Desired display name for the minted Pet */
  petName: string;
}

export interface RevokeClaimCodeCommand {
  claimCodeId: ClaimCodeId;
  revokedByAdminId: string;
}

export interface IClaimCodeRepository {
  save(code: ClaimCode): Promise<void>;
  update(code: ClaimCode): Promise<void>;
  findById(id: ClaimCodeId): Promise<ClaimCode | null>;
  findByCode(token: string): Promise<ClaimCode | null>;
}

/**
 * ClaimService orchestrates the issuance and redemption of ClaimCodes.
 * On successful redemption it delegates Pet creation to PetService.
 */
export class ClaimService {
  constructor(
    private readonly claimCodeRepository: IClaimCodeRepository,
    private readonly petServiceCreatePet: (cmd: {
      ownerId: string;
      species: PetSpecies;
      name: string;
      rarityOverride?: PetRarity;
    }) => Promise<Pet>,
  ) {}

  /**
   * Issues a new ClaimCode and persists it.
   * Throws if expiresAt is in the past.
   * Returns the issued ClaimCode.
   */
  async issueCode(cmd: IssueClaimCodeCommand): Promise<ClaimCode> {
    throw new Error('Not implemented');
  }

  /**
   * Looks up a ClaimCode by its human-readable token,
   * validates it is redeemable, mints a Pet for the claiming user,
   * and marks the code as CLAIMED atomically.
   *
   * Throws:
   * - NotFoundError if the token does not exist
   * - ClaimCodeExpiredError if the code has expired
   * - ClaimCodeAlreadyRedeemedError if the code is not PENDING
   *
   * Returns the newly minted Pet.
   */
  async redeemCode(cmd: RedeemClaimCodeCommand): Promise<Pet> {
    throw new Error('Not implemented');
  }

  /**
   * Revokes an un-claimed ClaimCode.
   * Throws if the code has already been claimed.
   */
  async revokeCode(cmd: RevokeClaimCodeCommand): Promise<ClaimCode> {
    throw new Error('Not implemented');
  }

  /**
   * Expires all PENDING codes whose expiresAt has passed.
   * Intended to be called by a scheduled job.
   * Returns the number of codes expired.
   */
  async expireStaleCodes(now: Date): Promise<number> {
    throw new Error('Not implemented');
  }

  /**
   * Retrieves a ClaimCode by its ID for admin inspection.
   * Returns null if not found.
   */
  async getCodeById(id: ClaimCodeId): Promise<ClaimCode | null> {
    throw new Error('Not implemented');
  }
}
