// docs/blueprint/scaffold/src/application/arena/ArenaService.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.8.3

import { BattleRecord, BattleRecordId, BattleMode } from '../../domain/arena/BattleRecord';
import { PetId } from '../../domain/pet/Pet';

export interface IBattleRecordRepository {
  save(record: BattleRecord): Promise<void>;
  findById(id: BattleRecordId): Promise<BattleRecord | null>;
  findByPetId(petId: PetId, limit: number, offset: number): Promise<BattleRecord[]>;
}

export interface InitiateBattleCommand {
  challengerPetId: PetId;
  opponentPetId: PetId;
  mode: BattleMode;
  /** ID of the user initiating the challenge */
  initiatedByUserId: string;
}

export interface BattleResult {
  record: BattleRecord;
  /** XP awarded to the winner (0 on draw) */
  xpAwarded: number;
  /** Change in ranked points for challenger (negative if lost) */
  challengerRankedPointsDelta: number;
  /** Change in ranked points for opponent (negative if lost) */
  opponentRankedPointsDelta: number;
}

export interface GetBattleHistoryQuery {
  petId: PetId;
  limit?: number;
  offset?: number;
}

/**
 * ArenaService orchestrates the battle lifecycle:
 * validation → simulation → recording → XP/ranking award.
 */
export class ArenaService {
  constructor(
    private readonly battleRecordRepository: IBattleRecordRepository,
    private readonly getPetById: (id: PetId) => Promise<import('../../domain/pet/Pet').Pet>,
    private readonly awardExperience: (petId: PetId, xp: number) => Promise<void>,
  ) {}

  /**
   * Validates both pets are eligible (not retired, different owners in RANKED mode),
   * runs the battle simulation, persists the BattleRecord, and awards XP to the winner.
   *
   * Throws:
   * - PetNotFoundError if either pet does not exist
   * - PetRetiredError if either pet is retired
   * - SelfBattleError if both pets belong to the same owner in RANKED mode
   *
   * Returns a BattleResult containing the full record and point deltas.
   */
  async initiateBattle(cmd: InitiateBattleCommand): Promise<BattleResult> {
    throw new Error('Not implemented');
  }

  /**
   * Retrieves a single BattleRecord by ID.
   * Returns null if not found.
   */
  async getBattleById(id: BattleRecordId): Promise<BattleRecord | null> {
    throw new Error('Not implemented');
  }

  /**
   * Returns the battle history for a given pet, ordered by startedAt descending.
   */
  async getBattleHistory(query: GetBattleHistoryQuery): Promise<BattleRecord[]> {
    throw new Error('Not implemented');
  }

  /**
   * Pure battle simulation: takes two pet stat snapshots and returns
   * a sequence of RoundSnapshots and the winner's pet ID.
   * Extracted for unit-testability — no I/O.
   */
  simulateBattle(
    challengerPetId: PetId,
    opponentPetId: PetId,
    challengerStats: import('../../domain/pet/PetStats').PetStats,
    opponentStats: import('../../domain/pet/PetStats').PetStats,
  ): {
    winnerPetId: PetId | null;
    rounds: import('../../domain/arena/BattleRecord').RoundSnapshot[];
  } {
    throw new Error('Not implemented');
  }

  /**
   * Calculates the ranked point delta using an ELO-inspired formula.
   * Returns [challengerDelta, opponentDelta].
   */
  calculateRankedDelta(
    challengerPoints: number,
    opponentPoints: number,
    outcome: 'WIN' | 'LOSS' | 'DRAW',
  ): [number, number] {
    throw new Error('Not implemented');
  }
}
