// docs/blueprint/scaffold/src/presentation/routes/pet.routes.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.10.1

import { FastifyInstance, FastifyPluginOptions, FastifyRequest, FastifyReply } from 'fastify';
import { PetService } from '../../application/pet/PetService';

// ---------------------------------------------------------------------------
// Request / Response schemas (Fastify JSON Schema for validation & serialisation)
// ---------------------------------------------------------------------------

const createPetBodySchema = {
  type: 'object',
  required: ['ownerId', 'species', 'name'],
  properties: {
    ownerId:         { type: 'string', format: 'uuid' },
    species:         { type: 'string', enum: ['FLAMEWOLF', 'AQUASERPENT', 'STONEBEAR', 'THUNDERBIRD', 'SHADOWFOX'] },
    name:            { type: 'string', minLength: 1, maxLength: 24 },
    rarityOverride:  { type: 'string', enum: ['COMMON', 'RARE', 'EPIC', 'LEGENDARY'] },
  },
} as const;

const petIdParamsSchema = {
  type: 'object',
  required: ['petId'],
  properties: {
    petId: { type: 'string', format: 'uuid' },
  },
} as const;

const listPetsQuerySchema = {
  type: 'object',
  properties: {
    ownerId:    { type: 'string', format: 'uuid' },
    rarity:     { type: 'string', enum: ['COMMON', 'RARE', 'EPIC', 'LEGENDARY'] },
    isRetired:  { type: 'boolean' },
    limit:      { type: 'integer', minimum: 1, maximum: 100, default: 20 },
    offset:     { type: 'integer', minimum: 0, default: 0 },
  },
} as const;

const renamePetBodySchema = {
  type: 'object',
  required: ['newName', 'requestingUserId'],
  properties: {
    newName:            { type: 'string', minLength: 1, maxLength: 24 },
    requestingUserId:   { type: 'string', format: 'uuid' },
  },
} as const;

const transferPetBodySchema = {
  type: 'object',
  required: ['fromUserId', 'toUserId'],
  properties: {
    fromUserId: { type: 'string', format: 'uuid' },
    toUserId:   { type: 'string', format: 'uuid' },
  },
} as const;

const retirePetBodySchema = {
  type: 'object',
  required: ['requestingUserId'],
  properties: {
    requestingUserId: { type: 'string', format: 'uuid' },
  },
} as const;

// ---------------------------------------------------------------------------
// Route handlers
// ---------------------------------------------------------------------------

async function handleCreatePet(
  request: FastifyRequest<{ Body: { ownerId: string; species: string; name: string; rarityOverride?: string } }>,
  reply: FastifyReply,
  petService: PetService,
): Promise<void> {
  throw new Error('Not implemented');
}

async function handleGetPet(
  request: FastifyRequest<{ Params: { petId: string } }>,
  reply: FastifyReply,
  petService: PetService,
): Promise<void> {
  throw new Error('Not implemented');
}

async function handleListPets(
  request: FastifyRequest<{ Querystring: Record<string, unknown> }>,
  reply: FastifyReply,
  petService: PetService,
): Promise<void> {
  throw new Error('Not implemented');
}

async function handleRenamePet(
  request: FastifyRequest<{ Params: { petId: string }; Body: { newName: string; requestingUserId: string } }>,
  reply: FastifyReply,
  petService: PetService,
): Promise<void> {
  throw new Error('Not implemented');
}

async function handleTransferPet(
  request: FastifyRequest<{ Params: { petId: string }; Body: { fromUserId: string; toUserId: string } }>,
  reply: FastifyReply,
  petService: PetService,
): Promise<void> {
  throw new Error('Not implemented');
}

async function handleRetirePet(
  request: FastifyRequest<{ Params: { petId: string }; Body: { requestingUserId: string } }>,
  reply: FastifyReply,
  petService: PetService,
): Promise<void> {
  throw new Error('Not implemented');
}

// ---------------------------------------------------------------------------
// Plugin registration
// ---------------------------------------------------------------------------

/**
 * petRoutes registers all /pets endpoints on the Fastify instance.
 *
 * Endpoints:
 *   POST   /pets                    — mint a new pet
 *   GET    /pets                    — list pets (paginated + filtered)
 *   GET    /pets/:petId             — get pet by ID
 *   PATCH  /pets/:petId/name        — rename a pet
 *   POST   /pets/:petId/transfer    — transfer ownership
 *   POST   /pets/:petId/retire      — retire a pet
 */
export async function petRoutes(
  fastify: FastifyInstance,
  _opts: FastifyPluginOptions & { petService: PetService },
): Promise<void> {
  const { petService } = _opts;

  fastify.post(
    '/pets',
    { schema: { body: createPetBodySchema } },
    (req, reply) => handleCreatePet(req as FastifyRequest<{ Body: any }>, reply, petService),
  );

  fastify.get(
    '/pets',
    { schema: { querystring: listPetsQuerySchema } },
    (req, reply) => handleListPets(req as FastifyRequest<{ Querystring: any }>, reply, petService),
  );

  fastify.get(
    '/pets/:petId',
    { schema: { params: petIdParamsSchema } },
    (req, reply) => handleGetPet(req as FastifyRequest<{ Params: any }>, reply, petService),
  );

  fastify.patch(
    '/pets/:petId/name',
    { schema: { params: petIdParamsSchema, body: renamePetBodySchema } },
    (req, reply) => handleRenamePet(req as FastifyRequest<{ Params: any; Body: any }>, reply, petService),
  );

  fastify.post(
    '/pets/:petId/transfer',
    { schema: { params: petIdParamsSchema, body: transferPetBodySchema } },
    (req, reply) => handleTransferPet(req as FastifyRequest<{ Params: any; Body: any }>, reply, petService),
  );

  fastify.post(
    '/pets/:petId/retire',
    { schema: { params: petIdParamsSchema, body: retirePetBodySchema } },
    (req, reply) => handleRetirePet(req as FastifyRequest<{ Params: any; Body: any }>, reply, petService),
  );
}
