// cucumber.js — Cucumber-js configuration for pixel-pet-arena
// ⚠️ Auto-generated by gendoc-align-fix gencode (D4-L3 fix)
// Prevents @future/@wip scenarios from being executed in CI

const common = {
  require: ['features/support/**/*.ts', 'features/steps/**/*.ts'],
  requireModule: ['ts-node/register'],
  tags: 'not @future and not @wip',
  format: ['progress-bar', 'json:reports/cucumber-report.json'],
  formatOptions: { snippetInterface: 'async-await' },
};

const client = {
  ...common,
  require: ['features/client/support/**/*.ts', 'features/client/steps/**/*.ts'],
  paths: ['features/client/**/*.feature'],
};

module.exports = {
  default: {
    ...common,
    paths: ['features/*.feature'],
  },
  client: {
    ...client,
  },
  all: {
    ...common,
    require: [
      'features/support/**/*.ts',
      'features/steps/**/*.ts',
      'features/client/support/**/*.ts',
      'features/client/steps/**/*.ts',
    ],
    paths: ['features/*.feature', 'features/client/**/*.feature'],
  },
};
