// docs/blueprint/scaffold/src/application/marketplace/MarketplaceService.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.11–§4.12 + docs/API.md §5.6 Marketplace Endpoints
// Phase 3 — gated by FF_MARKETPLACE feature flag.

import { PetId } from '../../domain/pet/Pet';
import {
  MarketplaceListing,
  MarketplaceListingId,
} from '../../domain/marketplace/MarketplaceListing';
import {
  MarketplaceTransaction,
  MarketplaceTransactionId,
} from '../../domain/marketplace/MarketplaceTransaction';

/** Anti-flip protection window — CONSTANTS marketplace_trade_antiflip_protection_days = 7. */
export const ANTIFLIP_PROTECTION_DAYS = 7;

export interface CreateListingCommand {
  readonly petId: PetId;
  readonly sellerTokenHash: string;
  readonly priceCredits: number;
  readonly expiresAt?: Date | null;
}

export interface CancelListingCommand {
  readonly listingId: MarketplaceListingId;
  readonly sellerTokenHash: string;
}

export interface BuyListingCommand {
  readonly listingId: MarketplaceListingId;
  readonly buyerTokenHash: string;
  readonly now: Date;
}

export interface BuyListingResult {
  readonly transaction: MarketplaceTransaction;
  readonly newOwnerPetAccessTokenIssued: boolean;
}

export interface IMarketplaceListingRepository {
  save(listing: MarketplaceListing): Promise<void>;
  update(listing: MarketplaceListing): Promise<void>;
  findById(id: MarketplaceListingId): Promise<MarketplaceListing | null>;
  findActiveByPet(petId: PetId): Promise<MarketplaceListing | null>;
  listActive(filters: {
    minPrice?: number;
    maxPrice?: number;
    rarity?: string;
    cursor?: string;
    limit?: number;
  }): Promise<{ items: MarketplaceListing[]; nextCursor: string | null }>;
}

export interface IMarketplaceTransactionRepository {
  save(transaction: MarketplaceTransaction): Promise<void>;
  findById(id: MarketplaceTransactionId): Promise<MarketplaceTransaction | null>;
  findLatestByPet(petId: PetId): Promise<MarketplaceTransaction | null>;
  listByPet(petId: PetId, limit: number): Promise<MarketplaceTransaction[]>;
}

/**
 * MarketplaceService orchestrates the listing → buy → transaction flow.
 *
 * Buy invariants enforced (see EDD §4.11–§4.12):
 *   1. Listing must be 'active'
 *   2. Buyer != seller (compared by sellerTokenHash !== buyerTokenHash)
 *   3. Anti-flip: pet's most recent transaction.completedAt must be older
 *      than ANTIFLIP_PROTECTION_DAYS days
 *   4. fee = FLOOR(priceCredits * 0.05)
 *   5. Listing.markSold() and Transaction.record() are persisted in a single
 *      transaction with the unique-constraint on (listing_id) acting as the
 *      authoritative idempotency guard.
 */
export class MarketplaceService {
  constructor(
    private readonly listings: IMarketplaceListingRepository,
    private readonly transactions: IMarketplaceTransactionRepository,
  ) {}

  /**
   * Creates a new listing if pet has no existing active listing AND price
   * satisfies the min-price formula.
   */
  async createListing(_cmd: CreateListingCommand): Promise<MarketplaceListing> {
    throw new Error('Not implemented');
  }

  /**
   * Cancels an active listing. Throws if the listing is not active or if the
   * sellerTokenHash does not match.
   */
  async cancelListing(_cmd: CancelListingCommand): Promise<MarketplaceListing> {
    throw new Error('Not implemented');
  }

  /**
   * Executes a purchase atomically. Performs anti-flip + self-trade checks
   * before persisting MarketplaceTransaction and updating the listing.
   */
  async buyListing(_cmd: BuyListingCommand): Promise<BuyListingResult> {
    throw new Error('Not implemented');
  }

  /**
   * Returns the trade history for a pet, newest first. Caller MUST verify
   * the requesting token currently owns the pet (handled at route layer).
   */
  async getHistoryForPet(petId: PetId, limit = 20): Promise<MarketplaceTransaction[]> {
    return this.transactions.listByPet(petId, limit);
  }
}
