// docs/blueprint/scaffold/src/domain/pet/Pet.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.5.1

import { PetRarity } from './PetRarity';
import { PetStats } from './PetStats';

export type PetId = string; // UUID v4

export type PetSpecies =
  | 'FLAMEWOLF'
  | 'AQUASERPENT'
  | 'STONEBEAR'
  | 'THUNDERBIRD'
  | 'SHADOWFOX';

export interface PetProps {
  readonly id: PetId;
  readonly ownerId: string;       // User ID of the current owner
  readonly species: PetSpecies;
  readonly rarity: PetRarity;
  readonly name: string;           // Display name, 1–24 chars
  readonly stats: PetStats;
  readonly isRetired: boolean;     // Retired pets cannot battle
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

/**
 * Pet is the core aggregate root of the pixel-pet-arena domain.
 * All mutations return a new Pet instance (immutable pattern).
 */
export class Pet {
  readonly id: PetId;
  readonly ownerId: string;
  readonly species: PetSpecies;
  readonly rarity: PetRarity;
  readonly name: string;
  readonly stats: PetStats;
  readonly isRetired: boolean;
  readonly createdAt: Date;
  readonly updatedAt: Date;

  private constructor(props: PetProps) {
    this.id = props.id;
    this.ownerId = props.ownerId;
    this.species = props.species;
    this.rarity = props.rarity;
    this.name = props.name;
    this.stats = props.stats;
    this.isRetired = props.isRetired;
    this.createdAt = props.createdAt;
    this.updatedAt = props.updatedAt;
  }

  /**
   * Factory: creates a brand-new Pet from a claim event.
   * Assigns a random rarity via PetRarity.sampleRarity().
   * Throws if required props are invalid.
   */
  static create(props: Omit<PetProps, 'id' | 'createdAt' | 'updatedAt' | 'isRetired'>): Pet {
    throw new Error('Not implemented');
  }

  /**
   * Reconstitutes a Pet from a persistence snapshot.
   * Does not apply business rules — use for repository hydration only.
   */
  static reconstitute(props: PetProps): Pet {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new Pet with the updated name.
   * Throws if the name is blank or exceeds 24 characters.
   */
  rename(newName: string): Pet {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new Pet with XP applied to its stats.
   * Delegates to PetStats.addExperience().
   */
  gainExperience(xp: number): Pet {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new Pet with isRetired set to true.
   * Throws if the pet is already retired.
   */
  retire(): Pet {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new Pet transferred to a new owner.
   * Throws if the pet is retired.
   */
  transferTo(newOwnerId: string): Pet {
    throw new Error('Not implemented');
  }

  toJSON(): PetProps {
    throw new Error('Not implemented');
  }
}
