// docs/blueprint/scaffold/src/domain/pet/PetRarity.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.5.2

export enum PetRarity {
  COMMON = 'COMMON',      // 60% probability
  RARE = 'RARE',          // 25% probability
  EPIC = 'EPIC',          // 12% probability
  LEGENDARY = 'LEGENDARY' // 3% probability
}

export const RARITY_PROBABILITIES: Record<PetRarity, number> = {
  [PetRarity.COMMON]: 0.60,
  [PetRarity.RARE]: 0.25,
  [PetRarity.EPIC]: 0.12,
  [PetRarity.LEGENDARY]: 0.03,
};

/**
 * Returns a rarity level sampled from the probability distribution.
 * Implementation must use a cryptographically-safe RNG for fairness.
 */
export function sampleRarity(): PetRarity {
  throw new Error('Not implemented');
}
