// docs/blueprint/scaffold/src/domain/pet/PetStats.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.5.3

/**
 * PetStats is an immutable value object representing a pet's combat attributes.
 * All arithmetic operations return new PetStats instances.
 */
export interface PetStatsProps {
  readonly hp: number;        // Hit points (1–500)
  readonly attack: number;    // Attack power (1–200)
  readonly defense: number;   // Defence rating (1–200)
  readonly speed: number;     // Initiative/speed score (1–200)
  readonly level: number;     // Current level (1–100)
  readonly experience: number; // Accumulated XP toward next level
}

export class PetStats {
  readonly hp: number;
  readonly attack: number;
  readonly defense: number;
  readonly speed: number;
  readonly level: number;
  readonly experience: number;

  private constructor(props: PetStatsProps) {
    this.hp = props.hp;
    this.attack = props.attack;
    this.defense = props.defense;
    this.speed = props.speed;
    this.level = props.level;
    this.experience = props.experience;
  }

  /**
   * Factory: creates a validated PetStats value object.
   * Throws if any value is out of range.
   */
  static create(props: PetStatsProps): PetStats {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new PetStats with accumulated XP applied.
   * Triggers level-up logic if XP threshold is crossed.
   */
  addExperience(xp: number): PetStats {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new PetStats scaled for the given level.
   * Used during level-up to recalculate base stats.
   */
  scaleToLevel(level: number): PetStats {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new PetStats with reduced HP (clamped to 0).
   */
  takeDamage(amount: number): PetStats {
    throw new Error('Not implemented');
  }

  /** Whether this pet has been knocked out (hp === 0). */
  isDefeated(): boolean {
    throw new Error('Not implemented');
  }

  /** Equality check: two PetStats are equal when all fields match. */
  equals(other: PetStats): boolean {
    throw new Error('Not implemented');
  }

  toJSON(): PetStatsProps {
    throw new Error('Not implemented');
  }
}
