// docs/blueprint/scaffold/src/domain/claim/ClaimCode.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.6.1

import { PetRarity } from '../pet/PetRarity';
import { PetSpecies } from '../pet/Pet';

export type ClaimCodeId = string; // UUID v4

export type ClaimCodeStatus = 'PENDING' | 'CLAIMED' | 'EXPIRED' | 'REVOKED';

export interface ClaimCodeProps {
  readonly id: ClaimCodeId;
  readonly code: string;              // Human-readable token, e.g. "XFWR-4829-KQZL"
  readonly status: ClaimCodeStatus;
  readonly speciesOverride: PetSpecies | null;  // null = random species at claim time
  readonly rarityOverride: PetRarity | null;    // null = probabilistic rarity roll
  readonly claimedByUserId: string | null;
  readonly claimedAt: Date | null;
  readonly expiresAt: Date;
  readonly createdAt: Date;
}

/**
 * ClaimCode is an entity that represents a single-use token granting
 * the holder the right to mint one Pet.
 */
export class ClaimCode {
  readonly id: ClaimCodeId;
  readonly code: string;
  readonly status: ClaimCodeStatus;
  readonly speciesOverride: PetSpecies | null;
  readonly rarityOverride: PetRarity | null;
  readonly claimedByUserId: string | null;
  readonly claimedAt: Date | null;
  readonly expiresAt: Date;
  readonly createdAt: Date;

  private constructor(props: ClaimCodeProps) {
    this.id = props.id;
    this.code = props.code;
    this.status = props.status;
    this.speciesOverride = props.speciesOverride;
    this.rarityOverride = props.rarityOverride;
    this.claimedByUserId = props.claimedByUserId;
    this.claimedAt = props.claimedAt;
    this.expiresAt = props.expiresAt;
    this.createdAt = props.createdAt;
  }

  /**
   * Factory: issues a new ClaimCode.
   * Generates a cryptographically random human-readable token.
   * Throws if expiresAt is in the past.
   */
  static issue(props: {
    speciesOverride?: PetSpecies;
    rarityOverride?: PetRarity;
    expiresAt: Date;
  }): ClaimCode {
    throw new Error('Not implemented');
  }

  /**
   * Reconstitutes a ClaimCode from a persistence snapshot.
   */
  static reconstitute(props: ClaimCodeProps): ClaimCode {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new ClaimCode in CLAIMED status.
   * Throws if the code is not PENDING or has expired.
   */
  redeem(userId: string, at: Date): ClaimCode {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new ClaimCode in REVOKED status.
   * Throws if the code has already been claimed.
   */
  revoke(): ClaimCode {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new ClaimCode in EXPIRED status.
   * Idempotent — safe to call on already-expired codes.
   */
  expire(at: Date): ClaimCode {
    throw new Error('Not implemented');
  }

  /** True if the code is PENDING and has not yet passed expiresAt. */
  isRedeemable(at: Date): boolean {
    throw new Error('Not implemented');
  }

  toJSON(): ClaimCodeProps {
    throw new Error('Not implemented');
  }
}
