// docs/blueprint/scaffold/tests/unit/domain/claim/ClaimCode.test.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.6.1

import { describe, it, expect, beforeEach } from 'vitest';
import { ClaimCode } from '../../../../src/domain/claim/ClaimCode';
import { PetRarity } from '../../../../src/domain/pet/PetRarity';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function futureDate(offsetMs = 24 * 60 * 60 * 1000): Date {
  return new Date(Date.now() + offsetMs);
}

function pastDate(offsetMs = 24 * 60 * 60 * 1000): Date {
  return new Date(Date.now() - offsetMs);
}

function issueCode(overrides: Partial<Parameters<typeof ClaimCode.issue>[0]> = {}): ClaimCode {
  return ClaimCode.issue({
    expiresAt: futureDate(),
    ...overrides,
  });
}

// ---------------------------------------------------------------------------
// ClaimCode.issue
// ---------------------------------------------------------------------------

describe('ClaimCode.issue', () => {
  it('creates a code in PENDING status', () => {
    const code = issueCode();
    expect(code.status).toBe('PENDING');
  });

  it('generates a non-empty human-readable token', () => {
    const code = issueCode();
    expect(code.code).toBeTruthy();
    expect(typeof code.code).toBe('string');
  });

  it('assigns a UUID as the ID', () => {
    const code = issueCode();
    expect(code.id).toMatch(/^[0-9a-f-]{36}$/i);
  });

  it('stores the rarity override when provided', () => {
    const code = issueCode({ rarityOverride: PetRarity.LEGENDARY });
    expect(code.rarityOverride).toBe(PetRarity.LEGENDARY);
  });

  it('leaves rarityOverride as null when not provided', () => {
    const code = issueCode();
    expect(code.rarityOverride).toBeNull();
  });

  it('throws when expiresAt is in the past', () => {
    expect(() => issueCode({ expiresAt: pastDate() })).toThrow();
  });
});

// ---------------------------------------------------------------------------
// ClaimCode#redeem
// ---------------------------------------------------------------------------

describe('ClaimCode#redeem', () => {
  let code: ClaimCode;
  const userId = 'user-uuid-001';

  beforeEach(() => {
    code = issueCode();
  });

  it('returns a new ClaimCode in CLAIMED status', () => {
    const redeemed = code.redeem(userId, new Date());
    expect(redeemed.status).toBe('CLAIMED');
  });

  it('records the claiming user ID', () => {
    const redeemed = code.redeem(userId, new Date());
    expect(redeemed.claimedByUserId).toBe(userId);
  });

  it('records the claimedAt timestamp', () => {
    const at = new Date();
    const redeemed = code.redeem(userId, at);
    expect(redeemed.claimedAt).toEqual(at);
  });

  it('does not mutate the original code', () => {
    code.redeem(userId, new Date());
    expect(code.status).toBe('PENDING');
  });

  it('throws when the code is already CLAIMED', () => {
    const redeemed = code.redeem(userId, new Date());
    expect(() => redeemed.redeem('user-uuid-002', new Date())).toThrow();
  });

  it('throws when the code is REVOKED', () => {
    const revoked = code.revoke();
    expect(() => revoked.redeem(userId, new Date())).toThrow();
  });

  it('throws when the code has EXPIRED', () => {
    const expired = code.expire(new Date());
    expect(() => expired.redeem(userId, new Date())).toThrow();
  });
});

// ---------------------------------------------------------------------------
// ClaimCode#revoke
// ---------------------------------------------------------------------------

describe('ClaimCode#revoke', () => {
  it('returns a new ClaimCode in REVOKED status', () => {
    const code = issueCode();
    expect(code.revoke().status).toBe('REVOKED');
  });

  it('does not mutate the original code', () => {
    const code = issueCode();
    code.revoke();
    expect(code.status).toBe('PENDING');
  });

  it('throws when the code is already CLAIMED', () => {
    const code = issueCode().redeem('user-uuid-001', new Date());
    expect(() => code.revoke()).toThrow();
  });
});

// ---------------------------------------------------------------------------
// ClaimCode#isRedeemable
// ---------------------------------------------------------------------------

describe('ClaimCode#isRedeemable', () => {
  it('returns true for a PENDING non-expired code', () => {
    const code = issueCode({ expiresAt: futureDate() });
    expect(code.isRedeemable(new Date())).toBe(true);
  });

  it('returns false for an expired code', () => {
    const code = issueCode({ expiresAt: futureDate(1) }); // expires in 1ms
    const futureNow = new Date(Date.now() + 10_000);
    expect(code.isRedeemable(futureNow)).toBe(false);
  });

  it('returns false for a CLAIMED code', () => {
    const code = issueCode().redeem('user-uuid-001', new Date());
    expect(code.isRedeemable(new Date())).toBe(false);
  });

  it('returns false for a REVOKED code', () => {
    const code = issueCode().revoke();
    expect(code.isRedeemable(new Date())).toBe(false);
  });
});
