// docs/blueprint/scaffold/src/application/pet/PetService.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.8.1

import { Pet, PetId, PetSpecies } from '../../domain/pet/Pet';
import { PetRarity } from '../../domain/pet/PetRarity';
import { IPetRepository, PetFilters, PaginatedResult, PaginationOptions } from '../../infrastructure/repositories/PetRepository';

export interface CreatePetCommand {
  ownerId: string;
  species: PetSpecies;
  name: string;
  rarityOverride?: PetRarity; // provided when a ClaimCode specifies a rarity
}

export interface RenamePetCommand {
  petId: PetId;
  requestingUserId: string;
  newName: string;
}

export interface TransferPetCommand {
  petId: PetId;
  fromUserId: string;
  toUserId: string;
}

export interface RetirePetCommand {
  petId: PetId;
  requestingUserId: string;
}

export interface AwardExperienceCommand {
  petId: PetId;
  xp: number;
}

/**
 * PetService orchestrates use-cases related to the Pet aggregate.
 * It coordinates the domain model with the repository and any
 * domain events that must be emitted.
 */
export class PetService {
  constructor(private readonly petRepository: IPetRepository) {}

  /**
   * Mints a new Pet and persists it.
   * Applies probabilistic rarity unless rarityOverride is provided.
   * Returns the created Pet.
   */
  async createPet(cmd: CreatePetCommand): Promise<Pet> {
    throw new Error('Not implemented');
  }

  /**
   * Retrieves a single Pet by ID.
   * Throws a not-found error if no Pet exists with that ID.
   */
  async getPetById(petId: PetId): Promise<Pet> {
    throw new Error('Not implemented');
  }

  /**
   * Returns a paginated list of Pets matching the given filters.
   */
  async listPets(
    filters: PetFilters,
    pagination: PaginationOptions,
  ): Promise<PaginatedResult<Pet>> {
    throw new Error('Not implemented');
  }

  /**
   * Renames a Pet.
   * Throws if requestingUserId is not the Pet's owner.
   */
  async renamePet(cmd: RenamePetCommand): Promise<Pet> {
    throw new Error('Not implemented');
  }

  /**
   * Transfers ownership of a Pet from one user to another.
   * Throws if the Pet is retired or fromUserId is not the current owner.
   */
  async transferPet(cmd: TransferPetCommand): Promise<Pet> {
    throw new Error('Not implemented');
  }

  /**
   * Marks a Pet as retired, preventing it from entering battles.
   * Throws if the requestingUserId is not the owner.
   */
  async retirePet(cmd: RetirePetCommand): Promise<Pet> {
    throw new Error('Not implemented');
  }

  /**
   * Awards XP to a Pet following a battle result.
   * Called by ArenaService after a battle is recorded.
   * Returns the updated Pet (potentially levelled up).
   */
  async awardExperience(cmd: AwardExperienceCommand): Promise<Pet> {
    throw new Error('Not implemented');
  }
}
