// docs/blueprint/scaffold/src/infrastructure/repositories/PetRepository.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.9.1

import { Pet, PetId } from '../../domain/pet/Pet';
import { PetRarity } from '../../domain/pet/PetRarity';

export interface PetFilters {
  ownerId?: string;
  rarity?: PetRarity;
  isRetired?: boolean;
  species?: string;
}

export interface PaginationOptions {
  limit: number;    // max 100
  offset: number;
}

export interface PaginatedResult<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
}

/**
 * IPetRepository is the domain-layer contract for Pet persistence.
 * Infrastructure implementations (Postgres, in-memory, etc.) must satisfy
 * this interface without leaking storage details into the domain.
 */
export interface IPetRepository {
  /**
   * Persists a new Pet. Throws if a pet with the same ID already exists.
   */
  save(pet: Pet): Promise<void>;

  /**
   * Persists updates to an existing Pet.
   * Throws if no Pet with that ID exists.
   */
  update(pet: Pet): Promise<void>;

  /**
   * Retrieves a Pet by its ID.
   * Returns null if not found.
   */
  findById(id: PetId): Promise<Pet | null>;

  /**
   * Retrieves all Pets matching the given filters with pagination.
   */
  findAll(filters: PetFilters, pagination: PaginationOptions): Promise<PaginatedResult<Pet>>;

  /**
   * Retrieves all Pets belonging to the given owner.
   */
  findByOwner(ownerId: string, pagination: PaginationOptions): Promise<PaginatedResult<Pet>>;

  /**
   * Permanently removes a Pet record.
   * Throws if no Pet with that ID exists.
   */
  delete(id: PetId): Promise<void>;

  /**
   * Returns true if a Pet with the given ID exists.
   */
  exists(id: PetId): Promise<boolean>;
}

/**
 * InMemoryPetRepository is a test-double implementation of IPetRepository.
 * Do not use in production.
 */
export class InMemoryPetRepository implements IPetRepository {
  private readonly store = new Map<PetId, Pet>();

  async save(pet: Pet): Promise<void> {
    throw new Error('Not implemented');
  }

  async update(pet: Pet): Promise<void> {
    throw new Error('Not implemented');
  }

  async findById(id: PetId): Promise<Pet | null> {
    throw new Error('Not implemented');
  }

  async findAll(filters: PetFilters, pagination: PaginationOptions): Promise<PaginatedResult<Pet>> {
    throw new Error('Not implemented');
  }

  async findByOwner(ownerId: string, pagination: PaginationOptions): Promise<PaginatedResult<Pet>> {
    throw new Error('Not implemented');
  }

  async delete(id: PetId): Promise<void> {
    throw new Error('Not implemented');
  }

  async exists(id: PetId): Promise<boolean> {
    throw new Error('Not implemented');
  }
}
