// docs/blueprint/scaffold/src/domain/marketplace/ListingStatus.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.12 + docs/SCHEMA.md §2.8 marketplace_listings.status

/**
 * Lifecycle status of a MarketplaceListing.
 * Source: docs/SCHEMA.md §2.8 marketplace_listings.status CHECK constraint.
 *
 * - active:    open for purchase
 * - cancelled: seller withdrew the listing before sale
 * - sold:      transitioned via the buy flow; a MarketplaceTransaction was created
 */
export type ListingStatus = 'active' | 'cancelled' | 'sold';

export const LISTING_STATUS_VALUES: readonly ListingStatus[] = [
  'active',
  'cancelled',
  'sold',
] as const;
