// docs/blueprint/scaffold/src/domain/marketplace/MarketplaceListing.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.12 + docs/SCHEMA.md §2.8 marketplace_listings
// Stereotype: <<Entity>>
// Phase 3 — gated by FF_MARKETPLACE.

import { PetId } from '../pet/Pet';
import { PetRarity } from '../pet/PetRarity';
import { ListingStatus, LISTING_STATUS_VALUES } from './ListingStatus';

/** O(1) set used by reconstitute() to validate the persisted status enum. */
const LISTING_STATUS_VALUES_RUNTIME: ReadonlySet<string> = new Set<string>(LISTING_STATUS_VALUES);

export type MarketplaceListingId = string; // UUID v4

export interface MarketplaceListingProps {
  readonly id: MarketplaceListingId;
  readonly petId: PetId;
  readonly sellerTokenHash: string;       // SHA-256 hex; raw token never stored
  readonly priceCredits: number;          // > 0; must satisfy min-price formula
  readonly status: ListingStatus;
  readonly listedAt: Date;
  readonly expiresAt: Date | null;        // optional expiry; null = no expiry
  readonly completedAt: Date | null;      // set when status -> 'sold' | 'cancelled'
}

/**
 * Coefficients of the min-price formula:
 *   priceCredits >= (petLevel * LEVEL_COEFF) + (rarityMultiplier * RARITY_COEFF)
 * Source: docs/EDD.md §4.12; CONSTANTS TRADE_MIN_PRICE_FORMULA_*.
 */
export const MIN_PRICE_LEVEL_COEFF = 100;
export const MIN_PRICE_RARITY_COEFF = 500;

/** Rarity multiplier values (CONSTANTS RARITY_MULTIPLIER_*). */
export const RARITY_MULTIPLIER: Readonly<Record<PetRarity, number>> = {
  COMMON: 1,
  RARE: 2,
  EPIC: 4,
  LEGENDARY: 8,
};

/**
 * MarketplaceListing represents a pet offered for sale.
 * All mutations return a new instance (immutable pattern).
 */
export class MarketplaceListing {
  readonly id: MarketplaceListingId;
  readonly petId: PetId;
  readonly sellerTokenHash: string;
  readonly priceCredits: number;
  readonly status: ListingStatus;
  readonly listedAt: Date;
  readonly expiresAt: Date | null;
  readonly completedAt: Date | null;

  private constructor(props: MarketplaceListingProps) {
    this.id = props.id;
    this.petId = props.petId;
    this.sellerTokenHash = props.sellerTokenHash;
    this.priceCredits = props.priceCredits;
    this.status = props.status;
    this.listedAt = props.listedAt;
    this.expiresAt = props.expiresAt;
    this.completedAt = props.completedAt;
  }

  /**
   * Computes the minimum legal price for a pet of the given level + rarity.
   * Pure function — does NOT mutate.
   * Throws on invalid inputs: petLevel must be a positive integer in [1..100],
   * rarity must be a known PetRarity. This guards against NaN propagation
   * (RARITY_MULTIPLIER[rarity] is undefined for unknown keys).
   */
  static computeMinPriceCredits(petLevel: number, rarity: PetRarity): number {
    if (!Number.isInteger(petLevel) || petLevel < 1 || petLevel > 100) {
      throw new RangeError(`petLevel must be an integer in [1..100]; got ${petLevel}`);
    }
    const multiplier = RARITY_MULTIPLIER[rarity];
    if (typeof multiplier !== 'number') {
      throw new TypeError(`Unknown PetRarity: ${String(rarity)}`);
    }
    return petLevel * MIN_PRICE_LEVEL_COEFF + multiplier * MIN_PRICE_RARITY_COEFF;
  }

  /**
   * Factory: opens a new active listing.
   * Throws if priceCredits violates the min-price formula or if the seller
   * already has an active listing for this pet.
   */
  static open(_props: Omit<MarketplaceListingProps, 'id' | 'status' | 'listedAt' | 'completedAt'>): MarketplaceListing {
    throw new Error('Not implemented');
  }

  /**
   * Reconstitutes from persistence. Performs lightweight invariant checks that
   * are also enforced by the DB (chk price > 0, status enum, listed_at NOT NULL)
   * to fail fast on corrupted rows rather than letting bad state propagate.
   * Does NOT enforce business rules (e.g. min-price formula, anti-flip).
   */
  static reconstitute(props: MarketplaceListingProps): MarketplaceListing {
    if (!Number.isInteger(props.priceCredits) || props.priceCredits <= 0) {
      throw new RangeError(
        `MarketplaceListing.priceCredits must be a positive integer; got ${props.priceCredits}`,
      );
    }
    if (!LISTING_STATUS_VALUES_RUNTIME.has(props.status)) {
      throw new TypeError(`MarketplaceListing.status invalid: ${String(props.status)}`);
    }
    return new MarketplaceListing(props);
  }

  /**
   * Returns a new listing transitioned to 'cancelled'.
   * Throws if the current status is not 'active'.
   */
  cancel(_now: Date): MarketplaceListing {
    throw new Error('Not implemented');
  }

  /**
   * Returns a new listing transitioned to 'sold'.
   * Called by the buy flow at the moment a MarketplaceTransaction is persisted.
   * Throws if the current status is not 'active'.
   */
  markSold(_now: Date): MarketplaceListing {
    throw new Error('Not implemented');
  }

  isActive(): boolean {
    return this.status === 'active';
  }

  toJSON(): MarketplaceListingProps {
    return {
      id: this.id,
      petId: this.petId,
      sellerTokenHash: this.sellerTokenHash,
      priceCredits: this.priceCredits,
      status: this.status,
      listedAt: this.listedAt,
      expiresAt: this.expiresAt,
      completedAt: this.completedAt,
    };
  }
}
