// docs/blueprint/scaffold/src/domain/marketplace/MarketplaceTransaction.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.11 + docs/SCHEMA.md §2.9 marketplace_transactions
// Stereotype: <<Entity>>
// Renamed from legacy `TradeRecord` (commit ef5c3a9).
// Phase 3 — gated by FF_MARKETPLACE.

import { PetId } from '../pet/Pet';
import { MarketplaceListingId } from './MarketplaceListing';

export type MarketplaceTransactionId = string; // UUID v4

/** CONSTANTS trade_transaction_fee_percent = 5. */
export const PLATFORM_FEE_PERCENT = 5;

export interface MarketplaceTransactionProps {
  readonly id: MarketplaceTransactionId;
  readonly listingId: MarketplaceListingId;
  readonly petId: PetId;
  readonly sellerTokenHash: string;
  readonly buyerTokenHash: string;
  readonly priceCredits: number;       // > 0
  readonly feeCredits: number;         // >= 0; FLOOR(priceCredits * 0.05)
  readonly listedAt: Date;             // copied from the listing for audit
  readonly completedAt: Date;          // doubles as anti-flip reference
}

/**
 * MarketplaceTransaction is an immutable ledger entry for a completed
 * marketplace trade. Once created it MUST NOT be mutated; the buy flow
 * inserts exactly one row per listing (uq_marketplace_transactions_listing).
 */
export class MarketplaceTransaction {
  readonly id: MarketplaceTransactionId;
  readonly listingId: MarketplaceListingId;
  readonly petId: PetId;
  readonly sellerTokenHash: string;
  readonly buyerTokenHash: string;
  readonly priceCredits: number;
  readonly feeCredits: number;
  readonly listedAt: Date;
  readonly completedAt: Date;

  private constructor(props: MarketplaceTransactionProps) {
    this.id = props.id;
    this.listingId = props.listingId;
    this.petId = props.petId;
    this.sellerTokenHash = props.sellerTokenHash;
    this.buyerTokenHash = props.buyerTokenHash;
    this.priceCredits = props.priceCredits;
    this.feeCredits = props.feeCredits;
    this.listedAt = props.listedAt;
    this.completedAt = props.completedAt;
  }

  /**
   * Pure helper: computes the platform fee in credits from a price.
   * fee = FLOOR(priceCredits * 0.05). Returns 0 for prices below 20.
   */
  static computeFeeCredits(priceCredits: number): number {
    if (!Number.isInteger(priceCredits) || priceCredits <= 0) {
      throw new RangeError(`priceCredits must be a positive integer; got ${priceCredits}`);
    }
    return Math.floor((priceCredits * PLATFORM_FEE_PERCENT) / 100);
  }

  /**
   * Factory invoked by the buy flow.
   * Validates invariants:
   *   - priceCredits > 0
   *   - feeCredits === computeFeeCredits(priceCredits)
   *   - completedAt >= listedAt
   *   - sellerTokenHash !== buyerTokenHash (cannot self-trade)
   * Throws on violation.
   */
  static record(_props: Omit<MarketplaceTransactionProps, 'id'>): MarketplaceTransaction {
    throw new Error('Not implemented');
  }

  /**
   * Reconstitutes from persistence with light invariant checks (price > 0,
   * fee >= 0, completedAt >= listedAt). Does NOT re-validate business rules.
   */
  static reconstitute(props: MarketplaceTransactionProps): MarketplaceTransaction {
    if (!Number.isInteger(props.priceCredits) || props.priceCredits <= 0) {
      throw new RangeError(
        `priceCredits must be a positive integer; got ${props.priceCredits}`,
      );
    }
    if (!Number.isInteger(props.feeCredits) || props.feeCredits < 0) {
      throw new RangeError(`feeCredits must be a non-negative integer; got ${props.feeCredits}`);
    }
    if (props.completedAt.getTime() < props.listedAt.getTime()) {
      throw new RangeError('completedAt must be >= listedAt');
    }
    return new MarketplaceTransaction(props);
  }

  /** Net credits transferred to the seller (priceCredits − feeCredits). */
  netSellerCredits(): number {
    return this.priceCredits - this.feeCredits;
  }

  /**
   * Returns a public-safe projection. Excludes both token hashes — they are
   * sensitive internal join keys and MUST NOT be exposed via player APIs.
   */
  toPublicJSON(): Omit<MarketplaceTransactionProps, 'sellerTokenHash' | 'buyerTokenHash'> {
    return {
      id: this.id,
      listingId: this.listingId,
      petId: this.petId,
      priceCredits: this.priceCredits,
      feeCredits: this.feeCredits,
      listedAt: this.listedAt,
      completedAt: this.completedAt,
    };
  }
}
