// docs/blueprint/scaffold/tests/unit/domain/pet/Pet.test.ts
// Generated by gendoc-gen-contracts | Source: docs/EDD.md §4.5.1

import { describe, it, expect, beforeEach } from 'vitest';
import { Pet, PetSpecies } from '../../../../src/domain/pet/Pet';
import { PetRarity } from '../../../../src/domain/pet/PetRarity';
import { PetStats } from '../../../../src/domain/pet/PetStats';

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

function buildBaseStats(): PetStats {
  return PetStats.create({
    hp: 100,
    attack: 50,
    defense: 40,
    speed: 60,
    level: 1,
    experience: 0,
  });
}

function buildPet(overrides: Partial<Parameters<typeof Pet.create>[0]> = {}): Pet {
  return Pet.create({
    ownerId: 'user-uuid-001',
    species: 'FLAMEWOLF' as PetSpecies,
    rarity: PetRarity.COMMON,
    name: 'Blaze',
    stats: buildBaseStats(),
    ...overrides,
  });
}

// ---------------------------------------------------------------------------
// Pet.create
// ---------------------------------------------------------------------------

describe('Pet.create', () => {
  it('creates a pet with the expected properties', () => {
    // Arrange
    const ownerId = 'user-uuid-001';
    const species: PetSpecies = 'FLAMEWOLF';

    // Act
    const pet = buildPet({ ownerId, species });

    // Assert
    expect(pet.ownerId).toBe(ownerId);
    expect(pet.species).toBe(species);
    expect(pet.isRetired).toBe(false);
    expect(pet.id).toBeTruthy();
  });

  it('assigns a UUID as the pet ID', () => {
    const pet = buildPet();
    expect(pet.id).toMatch(/^[0-9a-f-]{36}$/i);
  });

  it('throws when name is empty', () => {
    expect(() => buildPet({ name: '' })).toThrow();
  });

  it('throws when name exceeds 24 characters', () => {
    expect(() => buildPet({ name: 'A'.repeat(25) })).toThrow();
  });
});

// ---------------------------------------------------------------------------
// Pet.rename
// ---------------------------------------------------------------------------

describe('Pet#rename', () => {
  let pet: Pet;

  beforeEach(() => {
    pet = buildPet();
  });

  it('returns a new Pet with the updated name', () => {
    // Arrange / Act
    const renamed = pet.rename('Inferno');

    // Assert
    expect(renamed.name).toBe('Inferno');
    expect(renamed.id).toBe(pet.id); // same identity
  });

  it('does not mutate the original pet', () => {
    pet.rename('Inferno');
    expect(pet.name).toBe('Blaze');
  });

  it('throws when the new name is empty', () => {
    expect(() => pet.rename('')).toThrow();
  });

  it('throws when the new name exceeds 24 characters', () => {
    expect(() => pet.rename('B'.repeat(25))).toThrow();
  });
});

// ---------------------------------------------------------------------------
// Pet#retire
// ---------------------------------------------------------------------------

describe('Pet#retire', () => {
  it('returns a new Pet with isRetired = true', () => {
    const pet = buildPet();
    const retired = pet.retire();
    expect(retired.isRetired).toBe(true);
  });

  it('does not mutate the original pet', () => {
    const pet = buildPet();
    pet.retire();
    expect(pet.isRetired).toBe(false);
  });

  it('throws when the pet is already retired', () => {
    const pet = buildPet().retire();
    expect(() => pet.retire()).toThrow();
  });
});

// ---------------------------------------------------------------------------
// Pet#transferTo
// ---------------------------------------------------------------------------

describe('Pet#transferTo', () => {
  it('returns a new Pet with the updated ownerId', () => {
    const pet = buildPet({ ownerId: 'user-A' });
    const transferred = pet.transferTo('user-B');
    expect(transferred.ownerId).toBe('user-B');
  });

  it('throws when the pet is retired', () => {
    const pet = buildPet().retire();
    expect(() => pet.transferTo('user-B')).toThrow();
  });
});

// ---------------------------------------------------------------------------
// Pet#gainExperience
// ---------------------------------------------------------------------------

describe('Pet#gainExperience', () => {
  it('returns a new Pet with updated stats', () => {
    const pet = buildPet();
    const levelled = pet.gainExperience(100);
    expect(levelled.stats.experience).toBeGreaterThanOrEqual(100);
  });

  it('does not mutate the original pet stats', () => {
    const pet = buildPet();
    const originalXp = pet.stats.experience;
    pet.gainExperience(100);
    expect(pet.stats.experience).toBe(originalXp);
  });
});
